image: maven:3.6.3-openjdk-11

definitions:
  steps:
    - step: &build-step
        name: SonarQube analysis
        caches:
          - maven
          - sonar
        script:
          - COMMIT_ID=$(git rev-parse --short HEAD)
          - mvn verify sonar:sonar
            -Drevision=${COMMIT_ID}
            -Dsonar.projectKey=venturedive_web-automation-framework_AYiQmTCmS_rGk7Q7_W6_
            -Dsonar.host.url=${SONAR_HOST_URL}
            -Dsonar.token=${SONAR_TOKEN}
            -Dsonar.projectVersion=${COMMIT_ID}
  caches:
    sonar: ~/.sonar

clone:
  depth: full

pipelines:
  branches:
    '{master}':
      - step: *build-step

    '{Base_code}':
      - step: *build-step

  pull-requests:
    '**':
      - step: *build-step